version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_lab
    hostname: "postgres"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5896:5432"
    volumes:
      - ./db_data:/var/lib/pgsql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
